#theme: jekyll-theme-architect

theme: jekyll-theme-cayman

title: Mitsuhisa Sato's home page

supervisor: Mitsuhisa Sato (Juntendo Univ/RIKEN Center for Computational Science)

github:
  is_project_page: false
